export const FONT_MAP = {
  'Inter': "'Inter', sans-serif",
  'Bebas Neue': "'Bebas Neue', cursive",
  'Roboto': "'Roboto', sans-serif",
  'sans-serif': 'sans-serif',
  'Open Sans': "'Open Sans', sans-serif",
  'Lato': "'Lato', sans-serif",
  'Sekuya': "'Sekuya', 'Cinzel', serif",
  'Roboto Mono': "'Roboto Mono', monospace",
  'Arimo': "'Arimo', sans-serif",
  'Montserrat': "'Montserrat', sans-serif",
  'Bitcount Prop Single': "'Bitcount Prop Single', 'Pixelify Sans', 'Silkscreen', cursive",
  'Rubik Spray Paint': "'Rubik Spray Paint', cursive",
  'Merriweather': "'Merriweather', serif",
  'Oswald': "'Oswald', sans-serif",
  'Edu VIC WA NT Hand Precursive': "'Edu VIC WA NT Hand Precursive', cursive",
  'Inconsolata': "'Inconsolata', monospace",
  'JetBrains Mono': "'JetBrains Mono', monospace",
  'Dancing Script': "'Dancing Script', cursive",
  'Caveat': "'Caveat', cursive",
  'Archivo Black': "'Archivo Black', sans-serif",
  'Black Ops One': "'Black Ops One', display",
  'Saira': "'Saira', sans-serif",
  'Changa One': "'Changa One', display",
  'Orbitron': "'Orbitron', sans-serif",
  'Indie Flower': "'Indie Flower', cursive"
};

export const FONT_FAMILIES = [
  { id: 'Inter', name: 'Inter (Default Clean Sans)', family: "'Inter', sans-serif" },
  { id: 'Bebas Neue', name: 'Bebas Neue (Bold Display)', family: "'Bebas Neue', cursive" },
  { id: 'Roboto', name: 'Roboto (Modern Sans)', family: "'Roboto', sans-serif" },
  { id: 'Open Sans', name: 'Open Sans (Neutral Sans)', family: "'Open Sans', sans-serif" },
  { id: 'Lato', name: 'Lato (Elegant Sans)', family: "'Lato', sans-serif" },
  { id: 'Sekuya', name: 'Sekuya (Luxury Serif)', family: "'Sekuya', 'Cinzel', serif" },
  { id: 'Roboto Mono', name: 'Roboto Mono (Developer Mono)', family: "'Roboto Mono', monospace" },
  { id: 'Arimo', name: 'Arimo (Clean Standard)', family: "'Arimo', sans-serif" },
  { id: 'Montserrat', name: 'Montserrat (Geometric Sans)', family: "'Montserrat', sans-serif" },
  { id: 'Bitcount Prop Single', name: 'Bitcount Prop (Retro Pixel)', family: "'Bitcount Prop Single', 'Pixelify Sans', 'Silkscreen', cursive" },
  { id: 'Rubik Spray Paint', name: 'Rubik Spray (Urban Graffiti)', family: "'Rubik Spray Paint', cursive" },
  { id: 'Merriweather', name: 'Merriweather (Classic Editorial Serif)', family: "'Merriweather', serif" },
  { id: 'Oswald', name: 'Oswald (Condensed Heavy)', family: "'Oswald', sans-serif" },
  { id: 'Edu VIC WA NT Hand Precursive', name: 'Edu Precursive (Handwritten Script)', family: "'Edu VIC WA NT Hand Precursive', cursive" },
  { id: 'Inconsolata', name: 'Inconsolata (Sleek Mono)', family: "'Inconsolata', monospace" },
  { id: 'JetBrains Mono', name: 'JetBrains Mono (Code Mono)', family: "'JetBrains Mono', monospace" },
  { id: 'Dancing Script', name: 'Dancing Script (Flowing Cursive)', family: "'Dancing Script', cursive" },
  { id: 'Caveat', name: 'Caveat (Casual Handwriting)', family: "'Caveat', cursive" },
  { id: 'Archivo Black', name: 'Archivo Black (Ultra Impact)', family: "'Archivo Black', sans-serif" },
  { id: 'Black Ops One', name: 'Black Ops One (Stencil Military)', family: "'Black Ops One', display" },
  { id: 'Saira', name: 'Saira (Technical Semi-Condensed)', family: "'Saira', sans-serif" },
  { id: 'Changa One', name: 'Changa One (Block Heavy)', family: "'Changa One', display" },
  { id: 'Orbitron', name: 'Orbitron (Futuristic Cyber)', family: "'Orbitron', sans-serif" },
  { id: 'Indie Flower', name: 'Indie Flower (Playful Sketch)', family: "'Indie Flower', cursive" }
];
